# Generated by Django 6.0.6 on 2026-06-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin / Manager'), ('SAFETY_OFFICER', 'Safety Officer / Supervisor')], default='SAFETY_OFFICER', max_length=30),
        ),
    ]
